[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bank_app = "6SYF6ntmVaHjsWc7E9WJ5deAXvHLT9Fzzv585sKWXc4a"
staking_app = "Ci8DKHWrT9uqhzoP3bnqTUwekU4MDPyufJzBUzSKJxaF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sang_blockchain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
